### ISSUE TITLE
No rewards!

### ISSUE THREAD

**Issue by acidage777** [ball-network/ssdcoin-blockchain#4]
Mining few days with 1399 plots, and 700ssd on mine stake. No rewards. Same with all versions.

**Comment by bagyra** [comment]
Hello. And I have the same problem. version 2.1.6
OS Windows. Volume 1 Petabyte, collateral 3325 SSD. Location Israel. Version 2.0.0 worked fine, but all subsequent versions do not catch blocks. What's happening?

**Comment by bagyra** [comment]
LOGS:
2024-02-29T04:28:41.822 full_node ssdcoin.server.start_service: ERROR    fatal uncaught exception: AttributeError: 'int' object has no attribute 'name'
Traceback (most recent call last):
  File "ssdcoin\util\log_exceptions.py", line 20, in log_exceptions
  File "ssdcoin\server\start_service.py", line 321, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 633, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 600, in run_forever
  File "asyncio\base_events.py", line 1860, in _run_once
  File "asyncio\windows_events.py", line 439, in select
  File "asyncio\windows_events.py", line 788, in _poll
  File "ssdcoin\server\start_service.py", line 309, in _accept_signal
AttributeError: 'int' object has no attribute 'name'

2024-02-29T04:48:53.677 full_node ssdcoin.full_node.mempool_manager: WARNING  updating the mempool using the slow-path. peak: 2388a1e849c10ff58ad422231e5589dc47ca265a0b71f48ca745dbb99c2f3de0 new-peak-prev: 160329f5bd74f087d9a36fd77791bc44626b293c0d034f23087e61205cb42719 coins: not set
2024-02-29T04:50:14.537 wallet ssdcoin.rpc.wallet_rpc_api : ERROR    Failed to get transaction f9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b.
Traceback (most recent call last):
  File "ssdcoin\rpc\wallet_rpc_api.py", line 1048, in get_transactions
AssertionError: Cannot find coin record for type 72 transaction 0xf9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b
2024-02-29T04:51:26.410 full_node ssdcoin.full_node.mempool_manager: WARNING  updating the mempool using the slow-path. peak: d3a93367639b6547d19ae6f89cbabb6a70dc25746362ee3812a9bdeb0304d84d new-peak-prev: 96c6f7b07b3ff9fb6fa3d3b405e37ea22b1253da1a9ce59a7b1907520f1d047e coins: set
2024-02-29T04:51:37.070 wallet ssdcoin.wallet.wallet_state_manager: ERROR    Failed to add coin_state: CoinState { coin: Coin { parent_coin_info: 236fc404074d347cc114a15622812e6ffa48b89b590f1ce3dfe4530755293d2d, puzzle_hash: 8517b687547cd8feb7895e3e7a1577a45c9afcd06b81c56cae1a7f1284ec2c0a, amount: 8000000000000 }, spent_height: Some(764570), created_height: Some(105405) }, error: Was not able to obtain solution None
Traceback (most recent call last):
  File "ssdcoin\wallet\wallet_state_manager.py", line 1699, in _add_coin_states
  File "ssdcoin\wallet\wallet_state_manager.py", line 786, in determine_coin_type
  File "ssdcoin\wallet\util\wallet_sync_utils.py", line 354, in fetch_coin_spend_for_coin_state
  File "ssdcoin\wallet\util\wallet_sync_utils.py", line 340, in fetch_coin_spend
ssdcoin.wallet.util.wallet_sync_utils.PeerRequestException: Was not able to obtain solution None
2024-02-29T04:51:37.086 wallet ssdcoin.wallet.wallet_node : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'NO_TRANSACTIONS_WHILE_SYNCING',
 'status': 3,
 'txid': '0x3f23411207c5122b6c321015dc430341ecda584375ed7a14cdb435ae9591ce00'}
2024-02-29T04:51:37.101 wallet ssdcoin.wallet.wallet_node : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'NO_TRANSACTIONS_WHILE_SYNCING',
 'status': 3,
 'txid': '0x62b7bccd4820dc57b5b8a67ee367bcd6f98661d7ace65ed41069b2444d9f2350'}
2024-02-29T04:51:37.170 wallet ssdcoin.wallet.wallet_node : WARNING  Peer None did not respond in time.
2024-02-29T04:51:37.170 wallet wallet_server              : WARNING  Banning 83.240.8.135 for 120 seconds
2024-02-29T04:51:37.170 wallet ssdcoin.wallet.wallet_node : WARNING  Peer None did not respond in time.
2024-02-29T04:51:37.170 wallet wallet_server              : WARNING  Banning 83.240.8.135 for 120 seconds
2024-02-29T04:51:37.170 wallet ssdcoin.wallet.wallet_node : WARNING  Peer PeerInfo(_ip=IPv4Address('120.198.35.222'), _port=30088) did not respond in time.
2024-02-29T04:51:37.170 wallet wallet_server              : WARNING  Banning 120.198.35.222 for 120 seconds
2024-02-29T04:51:37.170 wallet ssdcoin.wallet.wallet_node : WARNING  Peer None did not respond in time.
2024-02-29T04:51:37.186 wallet wallet_server              : WARNING  Banning 83.240.8.135 for 120 seconds
2024-02-29T04:51:37.186 wallet ssdcoin.wallet.wallet_node : WARNING  Peer PeerInfo(_ip=IPv4Address('120.198.35.222'), _port=30088) did not respond in time.
2024-02-29T04:51:37.186 wallet wallet_server              : WARNING  Banning 120.198.35.222 for 120 seconds
2024-02-29T04:51:37.186 wallet ssdcoin.wallet.wallet_node : WARNING  Peer None did not respond in time.
2024-02-29T04:51:37.186 wallet wallet_server              : WARNING  Banning 83.240.8.135 for 120 seconds
2024-02-29T04:51:37.186 wallet ssdcoin.wallet.wallet_node : WARNING  Peer PeerInfo(_ip=IPv4Address('120.198.35.222'), _port=30088) did not respond in time.
2024-02-29T04:51:37.186 wallet wallet_server              : WARNING  Banning 120.198.35.222 for 120 seconds
2024-02-29T04:51:37.186 wallet ssdcoin.wallet.wallet_node : WARNING  Peer None did not respond in time.
2024-02-29T04:51:37.186 wallet wallet_server              : WARNING  Banning 83.240.8.135 for 120 seconds
2024-02-29T04:51:37.186 wallet ssdcoin.wallet.wallet_node : WARNING  Peer PeerInfo(_ip=IPv4Address('120.198.35.222'), _port=30088) did not respond in time.
2024-02-29T04:51:37.186 wallet wallet_server              : WARNING  Banning 120.198.35.222 for 120 seconds
2024-02-29T04:51:37.201 wallet ssdcoin.wallet.wallet_node : WARNING  Peer None did not respond in time.
2024-02-29T04:51:37.201 wallet wallet_server              : WARNING  Banning 83.240.8.135 for 120 seconds
2024-02-29T04:51:37.201 wallet ssdcoin.wallet.wallet_node : WARNING  Peer PeerInfo(_ip=IPv4Address('120.198.35.222'), _port=30088) did not respond in time.
2024-02-29T04:51:37.201 wallet wallet_server              : WARNING  Banning 120.198.35.222 for 120 seconds
2024-02-29T04:51:37.201 wallet ssdcoin.wallet.wallet_node : WARNING  Peer None did not respond in time.
2024-02-29T04:51:37.201 wallet wallet_server              : WARNING  Banning 83.240.8.135 for 120 seconds
2024-02-29T04:51:37.201 wallet ssdcoin.wallet.wallet_node : WARNING  Peer PeerInfo(_ip=IPv4Address('120.198.35.222'), _port=30088) did not respond in time.
2024-02-29T04:51:37.201 wallet wallet_server              : WARNING  Banning 120.198.35.222 for 120 seconds
2024-02-29T04:51:37.201 wallet ssdcoin.wallet.wallet_node : WARNING  Peer None did not respond in time.
2024-02-29T04:51:37.201 wallet wallet_server              : WARNING  Banning 83.240.8.135 for 120 seconds
2024-02-29T04:51:37.201 wallet ssdcoin.wallet.wallet_node : WARNING  Peer PeerInfo(_ip=IPv4Address('120.198.35.222'), _port=30088) did not respond in time.
2024-02-29T04:51:37.217 wallet wallet_server              : WARNING  Banning 120.198.35.222 for 120 seconds
2024-02-29T04:51:37.217 wallet ssdcoin.wallet.wallet_node : WARNING  Peer PeerInfo(_ip=IPv4Address('120.198.35.222'), _port=30088) did not respond in time.
2024-02-29T04:51:37.217 wallet wallet_server              : WARNING  Banning 120.198.35.222 for 120 seconds
2024-02-29T04:51:37.217 wallet ssdcoin.wallet.wallet_node : WARNING  Peer None did not respond in time.
2024-02-29T04:51:37.217 wallet wallet_server              : WARNING  Banning 83.240.8.135 for 120 seconds
2024-02-29T04:51:37.233 wallet ssdcoin.wallet.wallet_node : WARNING  Peer None did not respond in time.
2024-02-29T04:51:37.233 wallet wallet_server              : WARNING  Banning 83.240.8.135 for 120 seconds
2024-02-29T04:51:37.265 wallet ssdcoin.wallet.wallet_node : WARNING  Peer PeerInfo(_ip=IPv4Address('120.198.35.222'), _port=30088) did not respond in time.
2024-02-29T04:51:37.265 wallet wallet_server              : WARNING  Banning 120.198.35.222 for 120 seconds
2024-02-29T04:51:37.267 wallet ssdcoin.wallet.wallet_node : WARNING  Peer None did not respond in time.
2024-02-29T04:51:37.267 wallet wallet_server              : WARNING  Banning 83.240.8.135 for 120 seconds
2024-02-29T04:51:37.267 wallet ssdcoin.wallet.wallet_node : WARNING  Peer None did not respond in time.
2024-02-29T04:51:37.267 wallet wallet_server              : WARNING  Banning 120.198.35.222 for 120 seconds
2024-02-29T04:51:37.275 wallet ssdcoin.wallet.wallet_node : WARNING  Peer None did not respond in time.
2024-02-29T04:51:37.277 wallet wallet_server              : WARNING  Banning 83.240.8.135 for 120 seconds
2024-02-29T04:51:37.277 wallet ssdcoin.wallet.wallet_node : WARNING  Peer None did not respond in time.
2024-02-29T04:51:37.277 wallet wallet_server              : WARNING  Banning 120.198.35.222 for 120 seconds
2024-02-29T04:51:37.277 wallet ssdcoin.wallet.wallet_node : WARNING  Peer None did not respond in time.
2024-02-29T04:51:37.277 wallet wallet_server              : WARNING  Banning 120.198.35.222 for 120 seconds
2024-02-29T04:51:37.285 wallet ssdcoin.wallet.wallet_node : WARNING  Peer None did not respond in time.
2024-02-29T04:51:37.285 wallet wallet_server              : WARNING  Banning 83.240.8.135 for 120 seconds
2024-02-29T04:51:37.934 full_node ssdcoin.full_node.mempool_manager: WARNING  updating the mempool using the slow-path. peak: 0963475ef88369bc79044bbb6af19f02900cbdb5ad7b820aa260d0a80a6de4ea new-peak-prev: 4089cdbd2f76341139bd8e0016f11a8b08871d1b459f482bf2ae5b9fbdbe2864 coins: set
2024-02-29T04:51:42.567 wallet ssdcoin.rpc.wallet_rpc_api : ERROR    Failed to get transaction f9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b.
Traceback (most recent call last):
  File "ssdcoin\rpc\wallet_rpc_api.py", line 1048, in get_transactions
AssertionError: Cannot find coin record for type 72 transaction 0xf9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b
2024-02-29T04:51:43.948 full_node ssdcoin.full_node.mempool_manager: WARNING  updating the mempool using the slow-path. peak: 5c2d314cda7c8cfbb9d062f34cf7acd5b559946b0a61093a6d2b940f9563b457 new-peak-prev: 3f01a88d27f2a46e9e885c136646129c804e37443eace9d3a8a8b2f96731b286 coins: set
2024-02-29T04:51:54.276 wallet ssdcoin.wallet.wallet_node : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'NO_TRANSACTIONS_WHILE_SYNCING',
 'status': 3,
 'txid': '0x3f23411207c5122b6c321015dc430341ecda584375ed7a14cdb435ae9591ce00'}
2024-02-29T04:51:54.276 wallet ssdcoin.wallet.wallet_node : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'NO_TRANSACTIONS_WHILE_SYNCING',
 'status': 3,
 'txid': '0x62b7bccd4820dc57b5b8a67ee367bcd6f98661d7ace65ed41069b2444d9f2350'}

2024-02-29T19:44:46.148 wallet ssdcoin.wallet.wallet_state_manager: ERROR    Stake coin f9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b is already in a pending spend bundle. {'additions': [{'amount': 3228000000000000,
                'parent_coin_info': '0x6d7a9df108a4920f02c2caa3747c2b5d34909986eaae2340dc1aae051117e0c7',
                'puzzle_hash': '0xa7a1d423fbc4a18066bedb3ea5c3e719fd8d1eaea324fcb0c3651788340e678f'}],
 'amount': 3228000000000000,
 'confirmed': False,
 'confirmed_at_height': 777787,
 'created_at_time': 1708969449,
 'fee_amount': 0,
 'memos': [['0xf9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b',
            ['0x8517b687547cd8feb7895e3e7a1577a45c9afcd06b81c56cae1a7f1284ec2c0a']]],
 'name': '0xf9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b',
 'removals': [{'amount': 1750000000000,
               'parent_coin_info': '0xeff11dcd33c1bed70b36c3b24691e12949b00e4ae54bd6bf511028229f4ac0a5',
               'puzzle_hash': '0xc4b0c8efb7ce7334d80dafa472701f0e77f0fb3b99f3c305de357197b003f51f'}],
 'sent': 1,
 'sent_to': [],
 'spend_bundle': None,
 'to_puzzle_hash': '0x8517b687547cd8feb7895e3e7a1577a45c9afcd06b81c56cae1a7f1284ec2c0a',
 'trade_id': None,
 'type': 72,
 'valid_times': {'max_blocks_after_created': None,
                 'max_height': None,
                 'max_secs_after_created': None,
                 'max_time': None,
                 'min_blocks_since_created': None,
                 'min_height': None,
                 'min_secs_since_created': None,
                 'min_time': None},
 'wallet_id': 1}
2024-02-29T19:44:50.616 wallet ssdcoin.wallet.wallet_state_manager: ERROR    Stake coin f9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b is already in a pending spend bundle. {'additions': [{'amount': 3228000000000000,
                'parent_coin_info': '0x6d7a9df108a4920f02c2caa3747c2b5d34909986eaae2340dc1aae051117e0c7',
                'puzzle_hash': '0xa7a1d423fbc4a18066bedb3ea5c3e719fd8d1eaea324fcb0c3651788340e678f'}],
 'amount': 3228000000000000,
 'confirmed': False,
 'confirmed_at_height': 777787,
 'created_at_time': 1708969449,
 'fee_amount': 0,
 'memos': [['0xf9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b',
            ['0x8517b687547cd8feb7895e3e7a1577a45c9afcd06b81c56cae1a7f1284ec2c0a']]],
 'name': '0xf9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b',
 'removals': [{'amount': 1750000000000,
               'parent_coin_info': '0xeff11dcd33c1bed70b36c3b24691e12949b00e4ae54bd6bf511028229f4ac0a5',
               'puzzle_hash': '0xc4b0c8efb7ce7334d80dafa472701f0e77f0fb3b99f3c305de357197b003f51f'}],
 'sent': 1,
 'sent_to': [],
 'spend_bundle': None,
 'to_puzzle_hash': '0x8517b687547cd8feb7895e3e7a1577a45c9afcd06b81c56cae1a7f1284ec2c0a',
 'trade_id': None,
 'type': 72,
 'valid_times': {'max_blocks_after_created': None,
                 'max_height': None,
                 'max_secs_after_created': None,
                 'max_time': None,
                 'min_blocks_since_created': None,
                 'min_height': None,
                 'min_secs_since_created': None,
                 'min_time': None},
 'wallet_id': 1}
2024-02-29T19:44:58.194 wallet ssdcoin.wallet.wallet_state_manager: ERROR    Stake coin f9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b is already in a pending spend bundle. {'additions': [{'amount': 3228000000000000,
                'parent_coin_info': '0x6d7a9df108a4920f02c2caa3747c2b5d34909986eaae2340dc1aae051117e0c7',
                'puzzle_hash': '0xa7a1d423fbc4a18066bedb3ea5c3e719fd8d1eaea324fcb0c3651788340e678f'}],
 'amount': 3228000000000000,
 'confirmed': False,
 'confirmed_at_height': 777787,
 'created_at_time': 1708969449,
 'fee_amount': 0,
 'memos': [['0xf9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b',
            ['0x8517b687547cd8feb7895e3e7a1577a45c9afcd06b81c56cae1a7f1284ec2c0a']]],
 'name': '0xf9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b',
 'removals': [{'amount': 1750000000000,
               'parent_coin_info': '0xeff11dcd33c1bed70b36c3b24691e12949b00e4ae54bd6bf511028229f4ac0a5',
               'puzzle_hash': '0xc4b0c8efb7ce7334d80dafa472701f0e77f0fb3b99f3c305de357197b003f51f'}],
 'sent': 2,
 'sent_to': [['', 2, None]],
 'spend_bundle': None,
 'to_puzzle_hash': '0x8517b687547cd8feb7895e3e7a1577a45c9afcd06b81c56cae1a7f1284ec2c0a',
 'trade_id': None,
 'type': 72,
 'valid_times': {'max_blocks_after_created': None,
                 'max_height': None,
                 'max_secs_after_created': None,
                 'max_time': None,
                 'min_blocks_since_created': None,
                 'min_height': None,
                 'min_secs_since_created': None,
                 'min_time': None},
 'wallet_id': 1}
2024-02-29T19:45:04.858 wallet ssdcoin.wallet.wallet_state_manager: ERROR    Stake coin f9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b is already in a pending spend bundle. {'additions': [{'amount': 3228000000000000,
                'parent_coin_info': '0x6d7a9df108a4920f02c2caa3747c2b5d34909986eaae2340dc1aae051117e0c7',
                'puzzle_hash': '0xa7a1d423fbc4a18066bedb3ea5c3e719fd8d1eaea324fcb0c3651788340e678f'}],
 'amount': 3228000000000000,
 'confirmed': False,
 'confirmed_at_height': 777787,
 'created_at_time': 1708969449,
 'fee_amount': 0,
 'memos': [['0xf9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b',
            ['0x8517b687547cd8feb7895e3e7a1577a45c9afcd06b81c56cae1a7f1284ec2c0a']]],
 'name': '0xf9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b',
 'removals': [{'amount': 1750000000000,
               'parent_coin_info': '0xeff11dcd33c1bed70b36c3b24691e12949b00e4ae54bd6bf511028229f4ac0a5',
               'puzzle_hash': '0xc4b0c8efb7ce7334d80dafa472701f0e77f0fb3b99f3c305de357197b003f51f'}],
 'sent': 2,
 'sent_to': [['', 2, None]],
 'spend_bundle': None,
 'to_puzzle_hash': '0x8517b687547cd8feb7895e3e7a1577a45c9afcd06b81c56cae1a7f1284ec2c0a',
 'trade_id': None,
 'type': 72,
 'valid_times': {'max_blocks_after_created': None,
                 'max_height': None,
                 'max_secs_after_created': None,
                 'max_time': None,
                 'min_blocks_since_created': None,
                 'min_height': None,
                 'min_secs_since_created': None,
                 'min_time': None},
 'wallet_id': 1}
2024-02-29T19:45:13.505 wallet ssdcoin.wallet.wallet_state_manager: ERROR    Stake coin f9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b is already in a pending spend bundle. {'additions': [{'amount': 3228000000000000,
                'parent_coin_info': '0x6d7a9df108a4920f02c2caa3747c2b5d34909986eaae2340dc1aae051117e0c7',
                'puzzle_hash': '0xa7a1d423fbc4a18066bedb3ea5c3e719fd8d1eaea324fcb0c3651788340e678f'}],
 'amount': 3228000000000000,
 'confirmed': False,
 'confirmed_at_height': 777787,
 'created_at_time': 1708969449,
 'fee_amount': 0,
 'memos': [['0xf9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b',
            ['0x8517b687547cd8feb7895e3e7a1577a45c9afcd06b81c56cae1a7f1284ec2c0a']]],
 'name': '0xf9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b',
 'removals': [{'amount': 1750000000000,
               'parent_coin_info': '0xeff11dcd33c1bed70b36c3b24691e12949b00e4ae54bd6bf511028229f4ac0a5',
               'puzzle_hash': '0xc4b0c8efb7ce7334d80dafa472701f0e77f0fb3b99f3c305de357197b003f51f'}],
 'sent': 2,
 'sent_to': [['', 2, None], ['', 2, None]],
 'spend_bundle': None,
 'to_puzzle_hash': '0x8517b687547cd8feb7895e3e7a1577a45c9afcd06b81c56cae1a7f1284ec2c0a',
 'trade_id': None,
 'type': 72,
 'valid_times': {'max_blocks_after_created': None,
                 'max_height': None,
                 'max_secs_after_created': None,
                 'max_time': None,
                 'min_blocks_since_created': None,
                 'min_height': None,
                 'min_secs_since_created': None,
                 'min_time': None},
 'wallet_id': 1}
2024-02-29T19:45:21.659 wallet ssdcoin.wallet.wallet_state_manager: ERROR    Stake coin f9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b is already in a pending spend bundle. {'additions': [{'amount': 3228000000000000,
                'parent_coin_info': '0x6d7a9df108a4920f02c2caa3747c2b5d34909986eaae2340dc1aae051117e0c7',
                'puzzle_hash': '0xa7a1d423fbc4a18066bedb3ea5c3e719fd8d1eaea324fcb0c3651788340e678f'}],
 'amount': 3228000000000000,
 'confirmed': False,
 'confirmed_at_height': 777787,
 'created_at_time': 1708969449,
 'fee_amount': 0,
 'memos': [['0xf9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b',
            ['0x8517b687547cd8feb7895e3e7a1577a45c9afcd06b81c56cae1a7f1284ec2c0a']]],
 'name': '0xf9ed0108bd2ffe1ef1a7f60f8fd421ecefe43da209dc90aa8d100e854c73a96b',
 'removals': [{'amount': 1750000000000,
               'parent_coin_info': '0xeff11dcd33c1bed70b36c3b24691e12949b00e4ae54bd6bf511028229f4ac0a5',
               'puzzle_hash': '0xc4b0c8efb7ce7334d80dafa472701f0e77f0fb3b99f3c305de357197b003f51f'}],
 'sent': 2,
 'sent_to': [['', 2, None], ['', 2, None]],
 'spend_bundle': None,
 'to_puzzle_hash': '0x8517b687547cd8feb7895e3e7a1577a45c9afcd06b81c56cae1a7f1284ec2c0a',
 'trade_id': None,
 'type': 72,
 'valid_times': {'max_blocks_after_created': None,
                 'max_height': None,
                 'max_secs_after_created': None,
                 'max_time': None,
                 'min_blocks_since_created': None,
                 'min_height': None,
                 'min_secs_since_created': None,
                 'min_time': None},

**Comment by ball-network** [comment]
Please update your program to the latest version
